# Generated by Django 3.2.3 on 2021-05-30 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailChimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PictureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(max_length=25, verbose_name='Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail')),
                ('file', models.FileField(upload_to='', verbose_name='Images or Videos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.picturecategory')),
            ],
        ),
    ]
